services:
  - type: web
    name: seswa-fullstack
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://seswa2003:seswa2003@cluster0.z4t8igs.mongodb.net/seswa-db?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: seswa-super-secret-jwt-key-2024-production
      - key: JWT_EXPIRE
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: seswawb@gmail.com
      - key: EMAIL_FROM
        value: noreply@seswa.org
      - key: ADMIN_EMAIL
        value: seswawb@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
